### PR TITLE
Update stable Sugar version to 0.112

### PR DESCRIPTION
**Pull request by quozl**
For merge and promotion to production on 9th October after release announcement.

Reference: https://wiki.sugarlabs.org/go/Development_Team/Release#Glucose_.28base.29_modules

### CODE REVIEW

**Comment by quozl** [comment]
@scanterog, activities.sugarlabs.org is not offering 0.112 for compatible versions when uploading an activity.

**Comment by i5o** [comment]
@quozl that should be fixed now

**Comment by scanterog** [comment]
Hi @quozl. I just remembered that we need to change this in` site/app/config/config.php` which is not included in repo as we can see in [.gitignore](https://github.com/sugarlabs/aslo/blob/master/.gitignore#L15) file. I just recently updated it.

**Comment by quozl** [comment]
Thanks, I've tested, it is fixed.

**Pull request merged**
