### PR TITLE
Registration page alignment fixed

### PR DESCRIPTION
**Pull request by iamutkarshtiwari**
Textboxes moved below the respective tiles to give a clean look

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.

**Comment by iamutkarshtiwari** [comment]
@quozl Ping

**Comment by quozl** [comment]
What's the process for getting this change into production?

For sugarlabs.org, developer.sugarlabs.org, and help.sugarlabs.org we have automation set up, but I'd like to know what the automation is for activities.sugarlabs.org before I merge.

**Comment by iamutkarshtiwari** [comment]
@samswag @davelab6 @scanterog Please share some suggestions on how to get this change into production?

**Comment by quozl** [comment]
Mentioning also @icarito, in case of Sugar Network impact, as Sugar Network depends on ASLO and has huge user numbers.

**Comment by scanterog** [comment]
Currently there's no automatic deployment for production. We are using production branch into server. I can add a webhook and everytime someone add changes to production branch, deploy changes automatically into server, BUT someone must be responsible for checking changes before merging into production branch. I don't know when I'll have time to add this. Probably weekend.

**Comment by quozl** [comment]
@scanterog, thanks.  I'm not sure a web hook is worth it yet, we should wait for a higher change rate.  Perhaps release to production should be less regular than commits.  Please also review the pull request when you get time?

**Comment by icarito** [comment]
@quozl just a clarification, Sugar-Network doesn *not* depend on ASLO for anything. There used to be an ASLO sync script, and the plan was actually to have ASLO depend on Sugar Network. But currently they are not coupled or dependent in any way, except for the fact that Sugar Network pulls downloads from the same download locations as ASLO.

**Comment by quozl** [comment]
Thanks; no impact ASLO production, no impact Sugar Network.

@scanterog, how would you like "put this into production" requests?  Issues here?  systems@ mailing list?  Personal mail?

**Comment by scanterog** [comment]
So far I'm planning to check for new commits/PR every friday and put them into production. Does it sound good for you guys?

@quozl Thanks for merging. I'll merge into production branch after testing.

**Comment by iamutkarshtiwari** [comment]
@scanterog Sounds great! Thank you :)

**Comment by quozl** [comment]
@scanterog, thanks.  Feel free to push a git tag when you do.

**Pull request merged**
